theme: jekyll-theme-cayman
title: [Manifesto for Remote Agile Work]
description: [We are looking for the greatest remote teams and leaders to update the agile manifesto with our expierence and work reality in mind.]
